### PR TITLE
[ADD] Update "model" field in forecasting rule model. Now related field and add a domain to ir.filter field.

### LINKED ISSUE #38: Only show the ir.filter correspond to the forecast rule model
Add new domain that only show the filters related to the model defined in the model field.

Question: Also add a constraint?

### PR DESCRIPTION
**Pull request by zaoral**
Fix #38
Task [vx#4163](https://www.vauxoo.com/web#id=4163&view_type=form&model=project.task&action=138) HU [913](https://www.vauxoo.com/web#id=913&view_type=form&model=user.story&action=726) Sprint 20

### CODE REVIEW

**Comment by zaoral** [comment]
@nhomar this PR is ready to review.

**Comment by nhomar** [comment]
can you rebase this PR pliz

**Comment by zaoral** [comment]
@nhomar the rebase is ready. please review

**Comment by nhomar** [comment]
@zaoral for some reason it can not be merged yet.

can you rebase again pliz. (I just merged other newest commit).

**Comment by zaoral** [comment]
@nhomar. The cheks are green. Please review this PR.

**Pull request merged**
