### PR TITLE
[FIX] Add sudo() in forecast rule search

### PR DESCRIPTION
**Pull request by lescobarvx**
Fix Vauxoo/yoytec#1901
Close Vauxoo/yoytec#1918

---

This PR was created to fix the issue https://github.com/Vauxoo/yoytec/issues/1901

**Screenshot:**
error_filtro_cajero

### CODE REVIEW

**Comment by lescobarvx** [comment]
@zaoral 

Can you make technical review, please

**Comment by zaoral** [comment]
Hi @lescobarvx Please create a dummy PR in yoytec in order to test the new change as fixed

**Comment by zaoral** [comment]
Technical review +1
Functional review +1 more details in https://github.com/Vauxoo/yoytec/pull/1918#issuecomment-242581300

This PR is ready to be merged

@moylop260
Please can you help me with this merge?

> NOTE: The current change affect to one customer instance, this repository has fail all the checkers, I think this will be important to you:
- error 404 image
Complete log [here](http://runbot.vauxoo.com/runbot/static/build/16786-85-b805c4/logs/job_20_test_all.txt)
- travis lint errors that are not priority at this moment [build log](https://travis-ci.org/Vauxoo/forecast/jobs/155141667) and can be fixed later in #86

Best Regards

**Comment by moylop260** [comment]
screen shot 2016-08-25 at 7 32 33 pm

I can't merge it
Could you try it?

👍

**Comment by zaoral** [comment]
Neither can I. I have no permissions
image


@nhomar 
Please can you help us with this merge?

**Comment by nhomar** [comment]
Voy.

FYI este repo esta bloqueado para hacer merges sin pasar los tests (lo cual es el caso) por eso no tienen permisos.

**Comment by nhomar** [comment]
I disabled the force check but we need to fix this problems.

**Pull request merged**
